In [1]:
import pandas as pd
import numpy as np

numpy array

In [2]:
a1=np.arange(25).reshape(5,5)
print(a1)

df1=pd.DataFrame(a1)
df1


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

list of list

In [3]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
df2=pd.DataFrame(l1,columns=['a','b','c'],index=['r1','r2','r3'])
df2

a  b  c
r1  1  2  3
r2  4  5  6
r3  7  8  9

list of dict

In [4]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df1=pd.DataFrame(stock)
df1


name  price sector
0  apple    300   tech
1   ongc    500    oil
2  artil    400    oil

dict of list

In [5]:
stock={
    'name':['aapl','ongc','artil'],
    'price':['300','500','900'],
    'sector':['tech','oil','telecom']
}
df2=pd.DataFrame(stock)
df2.index=[44,55,66]
df2


name price   sector
44   aapl   300     tech
55   ongc   500      oil
66  artil   900  telecom

from csv

In [6]:
path=r"/Users/algo trading 2025/batch 31/9_data_analysis/sp500.csv"
df=pd.read_csv(path)
df.index=range(100,202)
df

Name                  Sector   Price    EPS
100                   Apple Inc  Information Technology  170.12   9.20
101                  Abbvie Inc             Health Care   93.29   5.31
102         Abbott Laboratories             Health Care   55.28   2.41
103               Accenture Plc  Information Technology  145.30   5.91
104                Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
197  Verizon Communications Inc      Telecommunications   45.85   3.75
198    Walgreens Boots Alliance        Consumer Staples   70.25   5.10
199       Wells Fargo & Company              Financials   54.02   4.14
200             Wal-Mart Stores        Consumer Staples   96.08   4.36
201            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

html

In [10]:
df=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]
df

Company name      Symbol  \
0                 Adani Enterprises    ADANIENT   
1                 Adani Ports & SEZ  ADANIPORTS   
2                  Apollo Hospitals  APOLLOHOSP   
3                      Asian Paints  ASIANPAINT   
4                         Axis Bank    AXISBANK   
5                        Bajaj Auto  BAJAJ-AUTO   
6                     Bajaj Finance  BAJFINANCE   
7                     Bajaj Finserv  BAJAJFINSV   
8                Bharat Electronics         BEL   
9                     Bharti Airtel  BHARTIARTL   
10                            Cipla       CIPLA   
11                       Coal India   COALINDIA   
12         Dr. Reddy's Laboratories     DRREDDY   
13                    Eicher Motors   EICHERMOT   
14                          Eternal     ETERNAL   
15                Grasim Industries      GRASIM   
16                          HCLTech     HCLTECH   
17                        HDFC Bank    HDFCBANK   
18                        HDFC Life    HDFCLIFE   
19                    Hero MotoCorp  HEROMOTOCO   
20              Hindalco Industries    HINDALCO   
21               Hindustan Unilever  HINDUNILVR   
22                       ICICI Bank   ICICIBANK   
23                    IndusInd Bank  INDUSINDBK   
24                          Infosys        INFY   
25                              ITC         ITC   
26           Jio Financial Services      JIOFIN   
27                        JSW Steel    JSWSTEEL   
28              Kotak Mahindra Bank   KOTAKBANK   
29                  Larsen & Toubro          LT   
30              Mahindra & Mahindra         M&M   
31                    Maruti Suzuki      MARUTI   
32                     Nestlé India   NESTLEIND   
33                             NTPC        NTPC   
34  Oil and Natural Gas Corporation        ONGC   
35                       Power Grid   POWERGRID   
36              Reliance Industries    RELIANCE   
37       SBI Life Insurance Company     SBILIFE   
38                  Shriram Finance  SHRIRAMFIN   
39              State Bank of India        SBIN   
40                       Sun Pharma   SUNPHARMA   
41        Tata Consultancy Services         TCS   
42           Tata Consumer Products  TATACONSUM   
43                      Tata Motors  TATAMOTORS   
44                       Tata Steel   TATASTEEL   
45                    Tech Mahindra       TECHM   
46                    Titan Company       TITAN   
47                            Trent       TRENT   
48                 UltraTech Cement  ULTRACEMCO   
49                            Wipro       WIPRO   

                        Sector[15]        Date added[16]  
0                  Metals & Mining     30 September 2022  
1                         Services     28 September 2015  
2                       Healthcare         31 March 2022  
3                Consumer Durables      27 April 2012[a]  
4               Financial Services         27 March 2009  
5   Automobile and Auto Components     1 October 2010[b]  
6               Financial Services     29 September 2017  
7               Financial Services          2 April 2018  
8                    Capital Goods     30 September 2024  
9                Telecommunication          1 March 2004  
10                      Healthcare        7 October 1998  
11     Oil, Gas & Consumable Fuels       10 October 2011  
12                      Healthcare     1 October 2010[c]  
13  Automobile and Auto Components          1 April 2016  
14               Consumer Services         28 March 2025  
15          Construction Materials       2 April 2018[d]  
16          Information Technology       28 October 2002  
17              Financial Services         22 April 1996  
18              Financial Services          31 July 2020  
19  Automobile and Auto Components     7 October 1998[e]  
20                 Metals & Mining         22 April 1996  
21      Fast Moving Consumer Goods         22 April 1996  
22              Financial Services       25 January 2002  
23   

In [9]:
!pip install lxml

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 6.9 MB/s eta 0:00:00a 0:00:01m

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [15]:
pd.read_excel('/Users/algo trading 2025/batch 31/9_data_analysis/Book1.xlsx')

11  22
0  33  44

In [14]:
!pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
