In [1]:
import pandas as pd
import numpy as np

numpy array

In [2]:
a1=np.arange(25).reshape(5,5)
print(a1)

df1=pd.DataFrame(a1)
df1


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

list of list

In [3]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
df2=pd.DataFrame(l1,columns=['a','b','c'],index=['r1','r2','r3'])
df2

a  b  c
r1  1  2  3
r2  4  5  6
r3  7  8  9

list of dict

In [4]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df1=pd.DataFrame(stock)
df1


name  price sector
0  apple    300   tech
1   ongc    500    oil
2  artil    400    oil

dict of list

In [5]:
stock={
    'name':['aapl','ongc','artil'],
    'price':['300','500','900'],
    'sector':['tech','oil','telecom']
}
df2=pd.DataFrame(stock)
df2.index=[44,55,66]
df2


name price   sector
44   aapl   300     tech
55   ongc   500      oil
66  artil   900  telecom

from csv

In [6]:
path=r"/Users/algo trading 2025/batch 31/9_data_analysis/sp500.csv"
df=pd.read_csv(path)
df.index=range(100,202)
df

Name                  Sector   Price    EPS
100                   Apple Inc  Information Technology  170.12   9.20
101                  Abbvie Inc             Health Care   93.29   5.31
102         Abbott Laboratories             Health Care   55.28   2.41
103               Accenture Plc  Information Technology  145.30   5.91
104                Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
197  Verizon Communications Inc      Telecommunications   45.85   3.75
198    Walgreens Boots Alliance        Consumer Staples   70.25   5.10
199       Wells Fargo & Company              Financials   54.02   4.14
200             Wal-Mart Stores        Consumer Staples   96.08   4.36
201            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

html

In [16]:
df5=pd.read_html('https://en.wikipedia.org/wiki/NIFTY_50')[1]
df5

Company name      Symbol  \
0                 Adani Enterprises    ADANIENT   
1                 Adani Ports & SEZ  ADANIPORTS   
2                  Apollo Hospitals  APOLLOHOSP   
3                      Asian Paints  ASIANPAINT   
4                         Axis Bank    AXISBANK   
5                        Bajaj Auto  BAJAJ-AUTO   
6                     Bajaj Finance  BAJFINANCE   
7                     Bajaj Finserv  BAJAJFINSV   
8                Bharat Electronics         BEL   
9                     Bharti Airtel  BHARTIARTL   
10                            Cipla       CIPLA   
11                       Coal India   COALINDIA   
12         Dr. Reddy's Laboratories     DRREDDY   
13                    Eicher Motors   EICHERMOT   
14                          Eternal     ETERNAL   
15                Grasim Industries      GRASIM   
16                          HCLTech     HCLTECH   
17                        HDFC Bank    HDFCBANK   
18                        HDFC Life    HDFCLIFE   
19                    Hero MotoCorp  HEROMOTOCO   
20              Hindalco Industries    HINDALCO   
21               Hindustan Unilever  HINDUNILVR   
22                       ICICI Bank   ICICIBANK   
23                    IndusInd Bank  INDUSINDBK   
24                          Infosys        INFY   
25                              ITC         ITC   
26           Jio Financial Services      JIOFIN   
27                        JSW Steel    JSWSTEEL   
28              Kotak Mahindra Bank   KOTAKBANK   
29                  Larsen & Toubro          LT   
30              Mahindra & Mahindra         M&M   
31                    Maruti Suzuki      MARUTI   
32                     Nestlé India   NESTLEIND   
33                             NTPC        NTPC   
34  Oil and Natural Gas Corporation        ONGC   
35                       Power Grid   POWERGRID   
36              Reliance Industries    RELIANCE   
37       SBI Life Insurance Company     SBILIFE   
38                  Shriram Finance  SHRIRAMFIN   
39              State Bank of India        SBIN   
40                       Sun Pharma   SUNPHARMA   
41        Tata Consultancy Services         TCS   
42           Tata Consumer Products  TATACONSUM   
43                      Tata Motors  TATAMOTORS   
44                       Tata Steel   TATASTEEL   
45                    Tech Mahindra       TECHM   
46                    Titan Company       TITAN   
47                            Trent       TRENT   
48                 UltraTech Cement  ULTRACEMCO   
49                            Wipro       WIPRO   

                        Sector[15]        Date added[16]  
0                  Metals & Mining     30 September 2022  
1                         Services     28 September 2015  
2                       Healthcare         31 March 2022  
3                Consumer Durables      27 April 2012[a]  
4               Financial Services         27 March 2009  
5   Automobile and Auto Components     1 October 2010[b]  
6               Financial Services     29 September 2017  
7               Financial Services          2 April 2018  
8                    Capital Goods     30 September 2024  
9                Telecommunication          1 March 2004  
10                      Healthcare        7 October 1998  
11     Oil, Gas & Consumable Fuels       10 October 2011  
12                      Healthcare     1 October 2010[c]  
13  Automobile and Auto Components          1 April 2016  
14               Consumer Services         28 March 2025  
15          Construction Materials       2 April 2018[d]  
16          Information Technology       28 October 2002  
17              Financial Services         22 April 1996  
18              Financial Services          31 July 2020  
19  Automobile and Auto Components     7 October 1998[e]  
20                 Metals & Mining         22 April 1996  
21      Fast Moving Consumer Goods         22 April 1996  
22              Financial Services       25 January 2002  
23   

In [9]:
!pip install lxml

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 6.9 MB/s eta 0:00:00a 0:00:01m

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [15]:
pd.read_excel('/Users/algo trading 2025/batch 31/9_data_analysis/Book1.xlsx')

11  22
0  33  44

In [14]:
!pip install openpyxl

  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [20]:
df5.index=range(200,250)
df5.columns=['name','symbol','sector','date']
df5

name      symbol  \
200                Adani Enterprises    ADANIENT   
201                Adani Ports & SEZ  ADANIPORTS   
202                 Apollo Hospitals  APOLLOHOSP   
203                     Asian Paints  ASIANPAINT   
204                        Axis Bank    AXISBANK   
205                       Bajaj Auto  BAJAJ-AUTO   
206                    Bajaj Finance  BAJFINANCE   
207                    Bajaj Finserv  BAJAJFINSV   
208               Bharat Electronics         BEL   
209                    Bharti Airtel  BHARTIARTL   
210                            Cipla       CIPLA   
211                       Coal India   COALINDIA   
212         Dr. Reddy's Laboratories     DRREDDY   
213                    Eicher Motors   EICHERMOT   
214                          Eternal     ETERNAL   
215                Grasim Industries      GRASIM   
216                          HCLTech     HCLTECH   
217                        HDFC Bank    HDFCBANK   
218                        HDFC Life    HDFCLIFE   
219                    Hero MotoCorp  HEROMOTOCO   
220              Hindalco Industries    HINDALCO   
221               Hindustan Unilever  HINDUNILVR   
222                       ICICI Bank   ICICIBANK   
223                    IndusInd Bank  INDUSINDBK   
224                          Infosys        INFY   
225                              ITC         ITC   
226           Jio Financial Services      JIOFIN   
227                        JSW Steel    JSWSTEEL   
228              Kotak Mahindra Bank   KOTAKBANK   
229                  Larsen & Toubro          LT   
230              Mahindra & Mahindra         M&M   
231                    Maruti Suzuki      MARUTI   
232                     Nestlé India   NESTLEIND   
233                             NTPC        NTPC   
234  Oil and Natural Gas Corporation        ONGC   
235                       Power Grid   POWERGRID   
236              Reliance Industries    RELIANCE   
237       SBI Life Insurance Company     SBILIFE   
238                  Shriram Finance  SHRIRAMFIN   
239              State Bank of India        SBIN   
240                       Sun Pharma   SUNPHARMA   
241        Tata Consultancy Services         TCS   
242           Tata Consumer Products  TATACONSUM   
243                      Tata Motors  TATAMOTORS   
244                       Tata Steel   TATASTEEL   
245                    Tech Mahindra       TECHM   
246                    Titan Company       TITAN   
247                            Trent       TRENT   
248                 UltraTech Cement  ULTRACEMCO   
249                            Wipro       WIPRO   

                             sector                  date  
200                 Metals & Mining     30 September 2022  
201                        Services     28 September 2015  
202                      Healthcare         31 March 2022  
203               Consumer Durables      27 April 2012[a]  
204              Financial Services         27 March 2009  
205  Automobile and Auto Components     1 October 2010[b]  
206              Financial Services     29 September 2017  
207              Financial Services          2 April 2018  
208                   Capital Goods     30 September 2024  
209               Telecommunication          1 March 2004  
210                      Healthcare        7 October 1998  
211     Oil, Gas & Consumable Fuels       10 October 2011  
212                      Healthcare     1 October 2010[c]  
213  Automobile and Auto Components          1 April 2016  
214               Consumer Services         28 March 2025  
215          Construction Materials       2 April 2018[d]  
216          Information Technology       28 October 2002  
217              Financial Services         22 April 1996  
218              Financial Services          31 July 2020  
219  Automobile and Auto Components     7 October 1998[e]  
220                 Metals & Mining         22 April 1996  
221      Fast Moving Consumer Goods         22 April 1996  

single column is called series
more than 1 column is called dataframe

In [22]:
df5['name']

200                  Adani Enterprises
201                  Adani Ports & SEZ
202                   Apollo Hospitals
203                       Asian Paints
204                          Axis Bank
205                         Bajaj Auto
206                      Bajaj Finance
207                      Bajaj Finserv
208                 Bharat Electronics
209                      Bharti Airtel
210                              Cipla
211                         Coal India
212           Dr. Reddy's Laboratories
213                      Eicher Motors
214                            Eternal
215                  Grasim Industries
216                            HCLTech
217                          HDFC Bank
218                          HDFC Life
219                      Hero MotoCorp
220                Hindalco Industries
221                 Hindustan Unilever
222                         ICICI Bank
223                      IndusInd Bank
224                            Infosys
225                      

In [27]:
df5.head(5)

name      symbol              sector               date
200  Adani Enterprises    ADANIENT     Metals & Mining  30 September 2022
201  Adani Ports & SEZ  ADANIPORTS            Services  28 September 2015
202   Apollo Hospitals  APOLLOHOSP          Healthcare      31 March 2022
203       Asian Paints  ASIANPAINT   Consumer Durables   27 April 2012[a]
204          Axis Bank    AXISBANK  Financial Services      27 March 2009

In [28]:
df5.tail(5)

name      symbol                  sector  \
245     Tech Mahindra       TECHM  Information Technology   
246     Titan Company       TITAN       Consumer Durables   
247             Trent       TRENT       Consumer Services   
248  UltraTech Cement  ULTRACEMCO  Construction Materials   
249             Wipro       WIPRO  Information Technology   

                     date  
245         28 March 2014  
246          2 April 2018  
247     30 September 2024  
248     28 September 2012  
249  27 September 2013[i]

In [29]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 200 to 249
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    50 non-null     object
 1   symbol  50 non-null     object
 2   sector  50 non-null     object
 3   date    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB


In [33]:
df6=pd.read_csv('https://raw.githubusercontent.com/sunilsala88/batch-29/main/10_data_analysis/sp500.csv')
df6.describe()

Price         EPS
count   102.000000  102.000000
mean    150.500686    6.485294
std     240.768463    8.577741
min      12.110000    0.020000
25%      54.335000    2.885000
50%      88.295000    4.405000
75%     151.032500    6.565000
max    1762.230000   74.450000

In [39]:
df6.shape

(102, 4)

In [40]:
df6.index

RangeIndex(start=0, stop=102, step=1)

In [41]:
df6.columns

Index(['Name', 'Sector', 'Price', 'EPS'], dtype='object')

subsetting

In [46]:
df6[['Name','Sector']]

Name                  Sector
0                     Apple Inc  Information Technology
1                    Abbvie Inc             Health Care
2           Abbott Laboratories             Health Care
3                 Accenture Plc  Information Technology
4                  Allergan Plc             Health Care
..                          ...                     ...
97   Verizon Communications Inc      Telecommunications
98     Walgreens Boots Alliance        Consumer Staples
99        Wells Fargo & Company              Financials
100             Wal-Mart Stores        Consumer Staples
101            Exxon Mobil Corp                  Energy

[102 rows x 2 columns]

In [50]:
df6.Sector

0      Information Technology
1                 Health Care
2                 Health Care
3      Information Technology
4                 Health Care
                ...          
97         Telecommunications
98           Consumer Staples
99                 Financials
100          Consumer Staples
101                    Energy
Name: Sector, Length: 102, dtype: object

filter data

In [55]:
df6[df6['Price']>200]

Name                  Sector    Price    EPS
8          Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
10          Boeing Company             Industrials   265.04   9.75
12              Biogen Inc             Health Care   311.92  21.59
14               Blackrock              Financials   474.05  21.55
20    Charter Communicatio  Consumer Discretionary   346.20   1.61
37              Fedex Corp             Industrials   217.75  11.91
44        Alphabet Class C  Information Technology  1018.48  29.87
45        Alphabet Class A  Information Technology  1034.09  29.87
46     Goldman Sachs Group              Financials   238.05  19.20
58    Lockheed Martin Corp             Industrials   312.93  12.72
65              3M Company             Industrials   232.49   8.95
75         Priceline Group  Consumer Discretionary  1762.23  74.45
91  Unitedhealth Group Inc             Health Care   209.75   9.60

In [59]:
df6[df6['EPS']>20]

Name                  Sector    Price    EPS
12        Biogen Inc             Health Care   311.92  21.59
14         Blackrock              Financials   474.05  21.55
44  Alphabet Class C  Information Technology  1018.48  29.87
45  Alphabet Class A  Information Technology  1034.09  29.87
75   Priceline Group  Consumer Discretionary  1762.23  74.45

In [62]:
a=df6['Price']>1000
b=df6['EPS']>20
df6[a & b]

Name                  Sector    Price    EPS
44  Alphabet Class C  Information Technology  1018.48  29.87
45  Alphabet Class A  Information Technology  1034.09  29.87
75   Priceline Group  Consumer Discretionary  1762.23  74.45

In [64]:
df6[(df6['Price']<100) & (df6['EPS']<10)]

Name                  Sector  Price   EPS
1                      Abbvie Inc             Health Care  93.29  5.31
2             Abbott Laboratories             Health Care  55.28  2.41
5    American International Group              Financials  59.50  2.51
9        American Express Company              Financials  93.92  5.22
11           Bank of America Corp              Financials  26.70  1.75
13   Bank of New York Mellon Corp              Financials  52.73  3.47
15   Bristol-Myers Squibb Company             Health Care  60.48  2.96
17                  Citigroup Inc              Financials  71.87  5.19
21      Colgate-Palmolive Company        Consumer Staples  72.16  2.87
22                 Comcast Corp A  Consumer Discretionary  36.13  2.02
23     Capital One Financial Corp              Financials  88.26  7.58
24                 Conocophillips                  Energy  49.89  0.02
26              Cisco Systems Inc  Information Technology  36.38  2.17
27                       CVS Corp        Consumer Staples  70.18  5.71
29                   Danaher Corp             Health Care  93.45  3.89
31               Duke Energy Corp               Utilities  88.61  4.45
32                 Dowdupont Inc.               Materials  71.12  3.66
33       Emerson Electric Company             Industrials  60.14  2.58
34                    Exelon Corp               Utilities  41.32  2.48
35             Ford Motor Company  Consumer Discretionary  12.11  1.68
38        21st Centry Fox Class B  Consumer Discretionary  30.42  1.92
39        21st Centry Fox Class A  Consumer Discretionary  31.14  1.92
41       General Electric Company             Industrials  17.91  1.24
42            Gilead Sciences Inc             Health Care  71.63  9.58
43         General Motors Company  Consumer Discretionary  44.74  6.19
47            Halliburton Company                  Energy  41.57  0.73
51                     Intel Corp  Information Technology  44.88  3.18
53           JP Morgan Chase & Co              Financials  98.58  6.94
54                 Kraft Heinz Co        Consumer Staples  80.59  3.56
55                  Kinder Morgan                  Energy  17.04  0.65
56              Coca-Cola Company        Consumer Staples  45.60  1.89
57          Eli Lilly and Company             Health Care  82.97  4.09
59               Lowe's Companies  Consumer Discretionary  81.43  4.34
62            Mondelez Intl Cmn A        Consumer Staples  42.49  2.05
63                  Medtronic Inc             Health Care  79.52  4.69
64                    Metlife Inc              Financials  51.85  5.20
66                   Altria Group        Consumer Staples  66.51  3.16
68                Merck & Company             Health Care  53.74  3.89
69                 Morgan Stanley              Financials  49.06  3.61
70                 Microsoft Corp  Information Technology  82.49  3.38
72                       Nike Inc  Consumer Discretionary  59.46  2.35
73                    Oracle Corp  Information Technology  48.97  2.55
74      Occidental Petroleum Corp                  Energy  68.17  0.35
77                     Pfizer Inc             Health Care  35.38  2.50
78       Procter & Gamble Company        Consumer Staples  88.33  3.98
80                Paypal Holdings  Information Technology  76.55  1.40
81                   Qualcomm Inc  Information Technology  66.83  3.78
83                 Starbucks Corp  Consumer Discretionary  56.83  2.07
84              Schlumberger N.V.                  Energy  61.53  1.29
85               Southern Company               Utilities  51.12  2.75
87                       AT&T Inc      Telecommunications  34.59  2.93
88                    Target Corp  Consumer Discretionary  57.77  4.93
89                Time Warner Inc  Consumer Discretionary  88.62  6.06
90              Texas Instruments  Information Technology  98.59  4.06
94                   U.S. Bancorp              Financials  51.88  3.37
97     Verizon Communications Inc      Telecommunicat

change index

In [70]:
df5=df5.set_index('name')

In [76]:
df5.set_index('sector',inplace=True)

In [77]:
df5

date
sector                                              
Metals & Mining                    30 September 2022
Services                           28 September 2015
Healthcare                             31 March 2022
Consumer Durables                   27 April 2012[a]
Financial Services                     27 March 2009
Automobile and Auto Components     1 October 2010[b]
Financial Services                 29 September 2017
Financial Services                      2 April 2018
Capital Goods                      30 September 2024
Telecommunication                       1 March 2004
Healthcare                            7 October 1998
Oil, Gas & Consumable Fuels          10 October 2011
Healthcare                         1 October 2010[c]
Automobile and Auto Components          1 April 2016
Consumer Services                      28 March 2025
Construction Materials               2 April 2018[d]
Information Technology               28 October 2002
Financial Services                     22 April 1996
Financial Services                      31 July 2020
Automobile and Auto Components     7 October 1998[e]
Metals & Mining                        22 April 1996
Fast Moving Consumer Goods             22 April 1996
Financial Services                   25 January 2002
Financial Services                      1 April 2013
Information Technology                7 October 1998
Fast Moving Consumer Goods             22 April 1996
Financial Services                     28 March 2025
Metals & Mining                    28 September 2018
Financial Services                      8 April 2010
Construction                     10 December 2004[f]
Automobile and Auto Components     18 September 1996
Automobile and Auto Components          1 March 2004
Fast Moving Consumer Goods      27 September 2019[g]
Power                              24 September 2007
Oil, Gas & Consumable Fuels            12 April 2004
Power                                  14 March 2008
Oil, Gas & Consumable Fuels            22 April 1996
Financial Services                 25 September 2020
Financial Services                     28 March 2024
Financial Services                     22 April 1996
Healthcare                           17 January 2002
Information Technology              25 February 2005
Fast Moving Consumer Goods          31 March 2021[h]
Automobile and Auto Components         22 April 1996
Metals & Mining                        22 April 1996
Information Technology                 28 March 2014
Consumer Durables                       2 April 2018
Consumer Services                  30 September 2024
Construction Materials             28 September 2012
Information Technology          27 September 2013[i]

In [79]:
df6.set_index('Name',inplace=True)

In [83]:
df6.reset_index(inplace=True)

In [84]:
df6

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]