In [1]:
import pandas as pd
import numpy as np

numpy array

In [3]:
a1=np.arange(25).reshape(5,5)
print(a1)

df1=pd.DataFrame(a1)
df1


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

list of list

In [5]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
df2=pd.DataFrame(l1,columns=['a','b','c'],index=['r1','r2','r3'])
df2

a  b  c
r1  1  2  3
r2  4  5  6
r3  7  8  9

list of dict

In [6]:
stock=[
    {"name":'apple' ,'price':300 ,'sector':'tech'},
    {"name":'ongc' ,'price':500 ,'sector':'oil'},
    {"name":'artil' ,'price':400 ,'sector':'oil',}
]
df1=pd.DataFrame(stock)
df1


name  price sector
0  apple    300   tech
1   ongc    500    oil
2  artil    400    oil

dict of list

In [7]:
stock={
    'name':['aapl','ongc','artil'],
    'price':['300','500','900'],
    'sector':['tech','oil','telecom']
}
df2=pd.DataFrame(stock)
df2


name price   sector
0   aapl   300     tech
1   ongc   500      oil
2  artil   900  telecom

from csv

In [8]:
path="/Users/algo trading 2025/batch 31/9_data_analysis/sp500.csv"
df=pd.read_csv(path)
df

Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30   5.91
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]